const GOALS = [
  { id: 1, name: "Reading 100 Books", type: "count", target: 100, increment: 1, unit: "books", category: "📚 Learning", emoji: "📖" },
  { id: 2, name: "TED 50 Video", type: "count", target: 50, increment: 1, unit: "videos", category: "📚 Learning", emoji: "🎥" },
  { id: 3, name: "100K Facebook", type: "followers", target: 100000, increment: 100, unit: "followers", category: "📱 Social Media", emoji: "👥" },
  { id: 4, name: "50K IG", type: "followers", target: 50000, increment: 100, unit: "followers", category: "📱 Social Media", emoji: "📸" },
  { id: 5, name: "10K WhatsApp", type: "followers", target: 10000, increment: 100, unit: "contacts", category: "📱 Social Media", emoji: "💬" },
  { id: 6, name: "25K LinkedIn", type: "followers", target: 25000, increment: 100, unit: "connections", category: "📱 Social Media", emoji: "💼" },
  { id: 7, name: "10,000$", type: "money", target: 10000, increment: 100, unit: "$", category: "💰 Financial", emoji: "💵" },
  { id: 8, name: "10K YouTube", type: "followers", target: 10000, increment: 100, unit: "subscribers", category: "📱 Social Media", emoji: "▶️" },
  { id: 9, name: "3 Times Quran Reciting", type: "count", target: 3, increment: 1, unit: "times", category: "🕌 Spiritual", emoji: "📿" },
  { id: 10, name: "Going to Thailand or any other country", type: "milestone", target: 1, increment: 1, unit: "", category: "✈️ Travel", emoji: "🌏" },
  { id: 11, name: "English / TOEFL", type: "milestone", target: 1, increment: 1, unit: "", category: "🎓 Academic", emoji: "🇬🇧" },
  { id: 12, name: "GRE", type: "milestone", target: 1, increment: 1, unit: "", category: "🎓 Academic", emoji: "📝" },
  { id: 13, name: "3 paper publish", type: "count", target: 3, increment: 1, unit: "papers", category: "🎓 Academic", emoji: "📄" },
  { id: 14, name: "20 coursera skills", type: "count", target: 20, increment: 1, unit: "courses", category: "📚 Learning", emoji: "🎓" },
  { id: 15, name: "GOT 2026", type: "milestone", target: 1, increment: 1, unit: "", category: "🎯 Career", emoji: "🏆" },
  { id: 16, name: "create 500 videos", type: "count", target: 500, increment: 1, unit: "videos", category: "🎬 Content", emoji: "📹" },
  { id: 17, name: "write my books (2)", type: "count", target: 2, increment: 1, unit: "books", category: "✍️ Writing", emoji: "📚" },
  { id: 18, name: "60 KG weigh", type: "milestone", target: 1, increment: 1, unit: "", category: "💪 Health", emoji: "⚖️" },
  { id: 19, name: "Asthi ba behesht", type: "milestone", target: 1, increment: 1, unit: "", category: "🕌 Spiritual", emoji: "🤲" },
  { id: 20, name: "Join 20 events", type: "count", target: 20, increment: 1, unit: "events", category: "🤝 Networking", emoji: "🎪" },
  { id: 21, name: "Public speaking 1000", type: "hours", target: 1000, increment: 1, unit: "hours", category: "🎤 Skills", emoji: "🗣️" },
  { id: 22, name: "learn photography 1000", type: "hours", target: 1000, increment: 1, unit: "hours", category: "🎤 Skills", emoji: "📷" },
  { id: 23, name: "AI skills 1000", type: "hours", target: 1000, increment: 1, unit: "hours", category: "🎤 Skills", emoji: "🤖" },
  { id: 24, name: "Video editing 1000", type: "hours", target: 1000, increment: 1, unit: "hours", category: "🎤 Skills", emoji: "✂️" },
  { id: 25, name: "chakar 2026", type: "milestone", target: 1, increment: 1, unit: "", category: "🎯 Career", emoji: "💼" },
  { id: 26, name: "Bekhar 2026", type: "milestone", target: 1, increment: 1, unit: "", category: "🎯 Career", emoji: "🎯" },
  { id: 27, name: "GOT university 2026", type: "milestone", target: 1, increment: 1, unit: "", category: "🎓 Academic", emoji: "🏫" },
  { id: 28, name: "GOT school 1000", type: "hours", target: 1000, increment: 1, unit: "hours", category: "🎓 Academic", emoji: "📖" },
  { id: 29, name: "Learn urdo", type: "count", target: 200, increment: 1, unit: "videos", category: "📚 Learning", emoji: "🇵🇰" },
  { id: 30, name: "3K telegram", type: "followers", target: 3000, increment: 100, unit: "members", category: "📱 Social Media", emoji: "✈️" },
  { id: 31, name: "everyday one min video", type: "count", target: 365, increment: 1, unit: "videos", category: "🎬 Content", emoji: "📱" },
  { id: 32, name: "20 movies for fun", type: "count", target: 20, increment: 1, unit: "movies", category: "🎭 Entertainment", emoji: "🎬" },
  { id: 33, name: "5 places to travel inside Malaysia", type: "count", target: 5, increment: 1, unit: "places", category: "✈️ Travel", emoji: "🗺️" },
  { id: 34, name: "GPA 3.8", type: "milestone", target: 1, increment: 1, unit: "", category: "🎓 Academic", emoji: "📊" },
  { id: 35, name: "50 urdo videos watch", type: "count", target: 50, increment: 1, unit: "videos", category: "📚 Learning", emoji: "📺" },
  { id: 36, name: "Only text contact officially", type: "milestone", target: 1, increment: 1, unit: "", category: "🎯 Personal", emoji: "📧" },
  { id: 37, name: "find away for long life ( Passport)", type: "milestone", target: 1, increment: 1, unit: "", category: "🎯 Personal", emoji: "🛂" },
  { id: 38, name: "YouTube monetization", type: "milestone", target: 1, increment: 1, unit: "", category: "💰 Financial", emoji: "💸" },
  { id: 39, name: "Take IELTS of TOFEL", type: "milestone", target: 1, increment: 1, unit: "", category: "🎓 Academic", emoji: "📜" },
  { id: 40, name: "work on my website", type: "milestone", target: 1, increment: 1, unit: "", category: "🎬 Content", emoji: "🌐" },
  { id: 41, name: "3 certifications skills", type: "count", target: 3, increment: 1, unit: "certs", category: "🎤 Skills", emoji: "🏅" },
  { id: 42, name: "Project Management certification", type: "milestone", target: 1, increment: 1, unit: "", category: "🎤 Skills", emoji: "📋" },
  { id: 43, name: "30 Days silence challenge", type: "count", target: 30, increment: 1, unit: "days", category: "🎯 Personal", emoji: "🤐" },
  { id: 44, name: "Monitoring, Evaluation certification", type: "milestone", target: 1, increment: 1, unit: "", category: "🎤 Skills", emoji: "📈" },
  { id: 45, name: "Research Methods & Academic Publishing 1000", type: "hours", target: 1000, increment: 1, unit: "hours", category: "🎓 Academic", emoji: "🔬" },
  { id: 46, name: "Strategic Planning & Theory of Change 1000", type: "hours", target: 1000, increment: 1, unit: "hours", category: "🎤 Skills", emoji: "🎯" },
  { id: 47, name: "Program Design & Curriculum Development 1000 / certification", type: "hours", target: 1000, increment: 1, unit: "hours", category: "🎓 Academic", emoji: "📋" },
  { id: 48, name: "Education Accreditation & Quality Assurance learning 1000", type: "hours", target: 1000, increment: 1, unit: "hours", category: "🎓 Academic", emoji: "✅" },
  { id: 49, name: "Academic Accreditation Processes (Regional & International)1000", type: "hours", target: 1000, increment: 1, unit: "hours", category: "🎓 Academic", emoji: "🌍" },
  { id: 50, name: "High-Level Negotiation & Influence (Cialdini/Harvard-Level)", type: "milestone", target: 1, increment: 1, unit: "", category: "🎤 Skills", emoji: "🤝" }
];

const config = {
  main_title: "My 2026 Goals",
  subtitle: "Track your progress to success",
  background_color: "#0a0e27",
  surface_color: "#1a1f3a",
  text_color: "#e2e8f0",
  primary_action_color: "#6366f1",
  secondary_action_color: "#475569",
  font_family: "Inter",
  font_size: 16
};

